### ISSUE TITLE
More than one button should be able to be assigned to an action

### ISSUE THREAD

**Issue by jni** [napari/midi-app-controller#104]
Not realising that one of the knobs is already assigned to zoom in/zoom out by default, I tried to assign these to the slider. I got this error:

```pytb
ValidationError: 1 validation error for Binds
  Value error, id=9 was bound to multiple actions [type=value_error, input_value={'name': 'Data annotation...ewer.camera.zoom_out'}]}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.8/v/value_error
```

Full traceback here:

https://gist.github.com/jni/2bbeeb97de3bd661ce9b7b6ef3926f54

Also, once I encountered this error, *it is impossible to start the plugin again*, and attempting to do so crashes napari.

It would be good if:

- multiple keys could be bound to the same action
- messing up the config could be recovered from
- the config location was documented so that it could be reset

Thank you! 🙏

**Comment by jni** [comment]
Ok I have made a smaller reproducer:

```python
from midi_app_controller.models.binds import Binds

data = {
    'name': 'Data annotation binds (2024-10-14 11-26-33.909782 copy)',
    'app_name': 'napari',
    'controller_name': 'X-TOUCH MINI',
    'description': 'Sample data annotation binds for X-TOUCH MINI',
    'button_binds': [
        {'button_id': 8, 'action_id': 'napari:layer:erase_mode'},
        {'button_id': 9, 'action_id': 'napari:layer:paint_mode'},
        {'button_id': 10, 'action_id': 'napari:layer:fill_mode'},
        {'button_id': 11, 'action_id': 'napari:layer:pan_zoom_mode'},
    ],
    'knob_binds': [
        {'knob_id': 1, 'action_id_increase': 'napari:viewer:increase_dimensions_right', 'action_id_decrease': 'napari:viewer:increase_dimensions_left'},
        {'knob_id': 2, 'action_id_increase': 'napari:layer:increase_brush_size', 'action_id_decrease': 'napari:layer:decrease_brush_size'},
        {'knob_id': 3, 'action_id_increase': 'napari:viewer:zoom_in', 'action_id_decrease': 'napari:viewer:zoom_out'},
        {'knob_id': 4, 'action_id_increase': 'napari:layer:increase_opacity', 'action_id_decrease': 'napari:layer:decrease_opacity'},
        {'knob_id': 5, 'action_id_increase': 'napari:layer:increase_gamma', 'action_id_decrease': 'napari:layer:decrease_gamma'},
        {'knob_id': 9, 'action_id_increase': 'napari.viewer.camera.zoom_in', 'action_id_decrease': 'napari.viewer.camera.zoom_out'},
    ],
}

b = Binds(**data)
```

**Comment by jni** [comment]
Replacing the last knob id with 6 instead of 9 makes the problem go away. Replacing any button id with an id used in the knob ids brings it back. It looks like the validator mistakenly looks for unique IDs across both knobs and buttons, which is incorrect.

**Comment by Czaki** [comment]
Take a look at the feature of highlight of knob and action in the settings dialog, as there may happen some 1-to-1 mapping.

**Comment by jni** [comment]
@Czaki I don't have the midi controller with me right now, will check shortly.

**Comment by jni** [comment]
@Czaki I have tested #105 settings with bi-directional highlighting and everything works as in main — only the knob buttons don't light up which I believe is the same as main.
