### ISSUE TITLE
pyproject.toml requests setuptools_scm but hardcodes version

### ISSUE THREAD

**Issue by jni** [napari/midi-app-controller#106]
The project version is hardcoded here:

https://github.com/napari/midi-app-controller/blob/cd96bf088c2aa75980f4e857236d439503d15653/pyproject.toml#L8

I believe to use setuptools_scm we should:

- use `dynamic = ['version']`
- use a `[tools.setuptools_scm]`section with `write_to = 'midi_app_controler/_version.py'`

Not sure whether I'm missing something. CC @Czaki

**Comment by Czaki** [comment]
agree
